In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy import stats
from datetime import date
import seaborn as sns
from pydataset import data
from env import host, user, password
import os
from acquire import acquire_zillow

## Acquire

In [2]:
df = acquire_zillow()

In [3]:
df

,parcelid,typeconstructiontypeid,storytypeid,propertylandusetypeid,heatingorsystemtypeid,buildingclasstypeid,architecturalstyletypeid,airconditioningtypeid,id,basementsqft,...,censustractandblock,max(logerror),transactiondate,airconditioningdesc,architecturalstyledesc,buildingclassdesc,heatingorsystemdesc,propertylandusedesc,storydesc,typeconstructiondesc
0,10711855,NaN,NaN,261.0,2.0,NaN,NaN,NaN,1087254,NaN,...,6.037113e+13,-0.007357,2017-07-07,None,None,None,Central,Single Family Residential,None,None
1,10711877,NaN,NaN,261.0,2.0,NaN,NaN,1.0,1072280,NaN,...,6.037113e+13,0.021066,2017-08-29,Central,None,None,Central,Single Family Residential,None,None
2,10711888,NaN,NaN,261.0,2.0,NaN,NaN,1.0,1340933,NaN,...,6.037113e+13,0.077174,2017-04-04,Central,None,None,Central,Single Family Residential,None,None
3,10711910,NaN,NaN,261.0,2.0,NaN,NaN,NaN,1878109,NaN,...,6.037113e+13,-0.041238,2017-03-17,None,None,None,Central,Single Family Residential,None,None
4,10711923,NaN,NaN,261.0,2.0,NaN,NaN,NaN,2190858,NaN,...,6.037113e+13,-0.009496,2017-03-24,None,None,None,Central,Single Family Residential,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77375,167686999,NaN,NaN,261.0,NaN,NaN,NaN,NaN,775695,NaN,...,NaN,-0.068632,2017-02-28,None,None,None,None,Single Family Residential,None,None
77376,167687739,NaN,NaN,266.0,NaN,NaN,NaN,NaN,2863262,NaN,...,NaN,0.360020,2017-03-03,None,None,None,None,Condominium,None,None
77377,167687839,NaN,NaN,261.0,NaN,NaN,NaN,NaN,1372384,NaN,...,NaN,0.038797,2017-05-31,None,None,None,None,Single Family Residential,None,None
77378,167688532,NaN,NaN,266.0,2.0,NaN,NaN,1.0,2758757,NaN,...,NaN,0.006706,2017-02-03,Central,None,None,Central,Condominium,None,None
77379,167689317,NaN,NaN,269.0,NaN,NaN,NaN,NaN,2535331,NaN,...,NaN,-0.008789,2017-03-14,None,None,None,None,Planned Unit Development,None,None

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77380 entries, 0 to 77379
Data columns (total 68 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   parcelid                      77380 non-null  int64
 1   typeconstructiontypeid        222 non-null    float64
 2   storytypeid                   50 non-null     float64
 3   propertylandusetypeid         77380 non-null  float64
 4   heatingorsystemtypeid         49439 non-null  float64
 5   buildingclasstypeid           15 non-null     float64
 6   architecturalstyletypeid      206 non-null    float64
 7   airconditioningtypeid         24953 non-null  float64
 8   id                            77380 non-null  int64
 9   basementsqft                  50 non-null     float64
 10  bathroomcnt                   77380 non-null  float64
 11  bedroomcnt                    77380 non-null  float64
 12  buildingqualitytypeid         49671 non-null  float64
 13  calculatedbathnbr             76771 non-null  float64
 14  decktypeid                    614 non-null    float64
 15  finishedfloor1squarefeet      6023 non-null   float64
 16  calculatedfinishedsquarefeet  77184 non-null  float64
 17  finishedsquarefeet12          73748 non-null  float64
 18  finishedsquarefeet13          41 non-null     float64
 19  finishedsquarefeet15          3009 non-null   float64
 20  finishedsquarefeet50          6023 non-null   float64
 21  finishedsquarefeet6           386 non-null    float64
 22  fips                          77380 non-null  float64
 23  fireplacecnt                  8276 non-null   float64
 24  fullbathcnt                   76771 non-null  float64
 25  garagecarcnt                  25474 non-null  float64
 26  garagetotalsqft               25474 non-null  float64
 27  hashottuborspa                1538 non-null   float64
 28  latitude                      77380 non-null  float64
 29  longitude                     77380 non-null  float64
 30  lotsizesquarefeet             69141 non-null  float64
 31  poolcnt                       16137 non-null  float64
 32  poolsizesum                   867 non-null    float64
 33  pooltypeid10                  464 non-null    float64
 34  pooltypeid2                   1074 non-null   float64
 35  pooltypeid7                   15042 non-null  float64
 36  propertycountylandusecode     77380 non-null  object
 37  propertyzoningdesc            50330 non-null  object
 38  rawcensustractandblock        77380 non-null  float64
 39  regionidcity                  75909 non-null  float64
 40  regionidcounty                77380 non-null  float64
 41  regionidneighborhood          30890 non-null  float64
 42  regionidzip                   77330 non-null  float64
 43  roomcnt                       77380 non-null  float64
 44  threequarterbathnbr           10096 non-null  float64
 45  unitcnt                       50562 non-null  float64
 46  yardbuildingsqft17            2388 non-null   float64
 47  yardbuildingsqft26            70 non-null     float64
 48  yearbuilt                     77117 non-null  float64
 49  numberofstories               17560 non-null  float64
 50  fireplaceflag                 172 non-null    float64
 51  structuretaxvaluedollarcnt    77268 non-null  float64
 52  taxvaluedollarcnt             77379 non-null  float64
 53  assessmentyear                77380 non-null  float64
 54  landtaxvaluedollarcnt         77378 non-null  float64
 55  taxamount                     77375 non-null  float64
 56  taxdelinquencyflag            2886 non-null   object
 57  taxdelinquencyyear            2886 non-null   float64
 58  censustractandblock           77136 non-null  float64
 59  max(logerror)                 77380 non-null  float64
 60  transactiondate               77380 non-null  object
 61  airconditioningdesc           24953 non-null  object
 62  architecturalstyledesc        206 non-null    object
 63  buildingclassdesc             15 non-null     object
 64  heatingorsystemdesc           49439 non-null  object
 65  propertylandusedesc           77380 non-null  object
 66  storydesc                     50 non-null     object
 67  typeconstructiondesc          222 non-null    object
dtypes: float64(55), int64(2), object(11)
memory usage: 40.1+ MB

In [5]:
df.shape

(77380, 68)

In [6]:
missing_stuff = pd.DataFrame(columns = ['rows_missing', 'perc_rows_missing'])
missing_stuff['rows_missing'] = df.isnull().sum()
missing_stuff['perc_rows_missing'] = round(((df.isnull().sum())/len(df)) * 100, 1)
missing_stuff

                              rows_missing  perc_rows_missing
parcelid                                 0                0.0
typeconstructiontypeid               77158               99.7
storytypeid                          77330               99.9
propertylandusetypeid                    0                0.0
heatingorsystemtypeid                27941               36.1
buildingclasstypeid                  77365              100.0
architecturalstyletypeid             77174               99.7
airconditioningtypeid                52427               67.8
id                                       0                0.0
basementsqft                         77330               99.9
bathroomcnt                              0                0.0
bedroomcnt                               0                0.0
buildingqualitytypeid                27709               35.8
calculatedbathnbr                      609                0.8
decktypeid                           76766               99.2
finishedfloor1squarefeet             71357               92.2
calculatedfinishedsquarefeet           196                0.3
finishedsquarefeet12                  3632                4.7
finishedsquarefeet13                 77339               99.9
finishedsquarefeet15                 74371               96.1
finishedsquarefeet50                 71357               92.2
finishedsquarefeet6                  76994               99.5
fips                                     0                0.0
fireplacecnt                         69104               89.3
fullbathcnt                            609                0.8
garagecarcnt                         51906               67.1
garagetotalsqft                      51906               67.1
hashottuborspa                       75842               98.0
latitude                                 0                0.0
longitude                                0                0.0
lotsizesquarefeet                     8239               10.6
poolcnt                              61243               79.1
poolsizesum                          76513               98.9
pooltypeid10                         76916               99.4
pooltypeid2                          76306               98.6
pooltypeid7                          62338               80.6
propertycountylandusecode                0                0.0
propertyzoningdesc                   27050               35.0
rawcensustractandblock                   0                0.0
regionidcity                          1471                1.9
regionidcounty                           0                0.0
regionidneighborhood                 46490               60.1
regionidzip                             50                0.1
roomcnt                                  0                0.0
threequarterbathnbr                  67284               87.0
unitcnt                              26818               34.7
yardbuildingsqft17                   74992               96.9
yardbuildingsqft26                   77310               99.9
yearbuilt                              263                0.3
numberofstories                      59820               77.3
fireplaceflag                        77208               99.8
structuretaxvaluedollarcnt             112                0.1
taxvaluedollarcnt                        1                0.0
assessmentyear                           0                0.0
landtaxvaluedollarcnt                    2                0.0
taxamount                                5                0.0
taxdelinquencyflag                   74494               96.3
taxdelinquencyyear                   74494               96.3
censustractandblock                    244                0.3
max(logerror)                            0                0.0
transactiondate                          0                0.0
airconditioningdesc                  52427               67.8
architecturalstyledesc               77174               99.7
buildingclassdesc                    77365              100.0
heatingorsystemdesc                  27941               36.1
propertylandusedesc                      0                0.0
storydesc                            77330               99.9
typeconstructiondesc                 77158               99.7

## Prep

In [7]:
# Specifying the single unit properties

df = df[(df['propertylandusetypeid'] == 261) | (df['propertylandusetypeid'] == 262) | (df['propertylandusetypeid'] == 263) | (df['propertylandusetypeid'] == 273) | (df['propertylandusetypeid'] == 275) | (df['propertylandusetypeid'] == 276) | (df['propertylandusetypeid'] == 279)]

In [8]:
# Specifying at least 1 bath, 1 bed, and 350 sq ft

df = df[(df.bedroomcnt > 0) & (df.bathroomcnt > 0) & ((df.unitcnt<=1)|df.unitcnt.isnull())\
            & (df.calculatedfinishedsquarefeet>350)]

In [9]:
def handle_missing_values(df, prop_required_column = .5, prop_required_row = .70):
    threshold = int(round(prop_required_column*len(df.index),0))
    df.dropna(axis=1, thresh=threshold, inplace=True)
    threshold = int(round(prop_required_row*len(df.columns),0))
    df.dropna(axis=0, thresh=threshold, inplace=True)
    return df

In [10]:
df = handle_missing_values(df)

In [11]:
df.drop(columns = ['finishedsquarefeet12', 'propertycountylandusecode', 'propertyzoningdesc',
                   'regionidcity', 'assessmentyear', 'id'], inplace = True)

In [12]:
df.fips.replace({6037: 'Los Angeles', 6059: 'Orange', 6111: 'Ventura'}, inplace = True)
df.rename(columns = {'fips': 'county'}, inplace = True)

In [13]:
df.unitcnt.fillna(1, inplace = True)

In [14]:
df.heatingorsystemdesc.fillna('None', inplace = True)

In [15]:
df.lotsizesquarefeet.fillna(7313, inplace = True)
df.buildingqualitytypeid.fillna(6.0, inplace = True)

In [17]:
df = df[df.taxvaluedollarcnt < 5_000_000]
df = df[df.calculatedfinishedsquarefeet < 8000]

In [4]:
def handle_outliers(db, column, k):
    Q1 = db[column].quantile(0.25)
    Q3 = db[column].quantile(0.75)
    IQR = Q3 - Q1
    db = db[(db[column] < (Q3 + (k * IQR)) & (db[column] > (Q1 - (k * IQR))))]

In [ ]:
def min_max_scaler(train, valid, test):
    num_vars = list(train.select_dtypes('number').columns)
    scaler = MinMaxScaler(copy=True, feature_range=(0,1))
    train[num_vars] = scaler.fit_transform(train[num_vars])
    valid[num_vars] = scaler.transform(valid[num_vars])
    test[num_vars] = scaler.transform(test[num_vars])
    return scaler, train, valid, test